title: "github_social_preview_pptx_template"
description: "A PPTX Template for GitHub Social Template."
baseurl: "/github_social_preview_pptx_template"
url: "https://europanite.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
highlighter: rouge